### ISSUE TITLE
点击节点隐藏兄弟节点

### ISSUE THREAD

**Issue by liangdianbo** [sangtian152/vue3-tree-org#10]
大佬好，

想实现点击某个节点，在该节点的click事件处理中，实现隐藏该节点兄弟节点及兄弟节点的所有子节点，然后再次点击该节点的父节点能够正常打开子级节点。

如下图
![image](https://user-images.githubusercontent.com/45776594/195241851-acc2dae4-6172-4474-8f4f-69c10ca3a13f.png)
点击_金融_节点把_实货_节点全部隐藏，再次点击_业务风险报表_，能正常显示_实货_和_金融_节点

有什么好的建议么

谢谢！

**Comment by sangtian152** [comment]
这，组件不支持这个功能，只能你自己研究一下怎么实现了，可以考虑一下点击节点的时候，把兄弟节点数据删除，点击父级节点再加回来
