### ISSUE TITLE
初始化和还原的的时候能居中吗大佬？

### ISSUE THREAD

**Issue by TaoziDeGitHub** [sangtian152/vue3-tree-org#11]
初始化和还原的的时候能居中吗大佬？

**Comment by sangtian152** [comment]
可以计算位置调用组件 onDragStop 方法设置偏移使居中，传两个参数x,y，都是数字类型

**Comment by pandly** [comment]
> 可以计算位置调用组件 onDragStop 方法设置偏移使居中，传两个参数x,y，都是数字类型

onDragStop不是一个事件吗？

**Comment by maqingbo** [comment]
可以设置全局样式：

```html
<style lang="scss">
.zoom-container {
  display: flex;
  justify-content: center;
  align-items: center;
}
</style>
```

![image](https://user-images.githubusercontent.com/20136852/209052289-e7bd8dc7-41ff-4822-930f-30b62a60f8d4.png)
