### ISSUE TITLE
vue3+vite + ts 打包报错

### ISSUE THREAD

**Issue by see-the-day** [sangtian152/vue3-tree-org#9]
Cannot find module '../../../utils/types' or its corresponding type declarations.

**Comment by sangtian152** [comment]
同vue3+vite + ts，[vue3-element-admin](https://github.com/sangtian152/vue3-element-admin)没有报错

**Comment by see-the-day** [comment]
![image](https://user-images.githubusercontent.com/33998390/195756296-3e870d51-9d8c-47a1-900d-de33349af41f.png)
这个文件我看在modules里面是没有的，但是没看懂你那个项目为什么不报错，用vite新搭一个引入应该是报错的

**Comment by see-the-day** [comment]
ts.config.json代码改成这个
`{
  "compilerOptions": {
    "composite": true,
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "suppressImplicitAnyIndexErrors": true,
    "lib": ["esnext", "dom"],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
}`
build 命令用 vue-tsc --noEmit && vite build 打包就会报错
json文件里面用references引用的话不会报错
